### ISSUE TITLE
Add ability to gzip/brotli files before uploading

### ISSUE THREAD

**Issue by chambo-e** [matthprost/s3-deploy-bucket-website-action#1]
And meta should be set appropriately

Would be nice to have that option :)

**Comment by matthprost** [comment]
This option is now available in v0.0.30 using parameter `COMPRESS_TOOL: gzip`. Only gzip is available from now but more will come soon :)

https://github.com/matthprost/s3-deploy-bucket-website-action/releases/tag/v0.0.30
